### ISSUE TITLE
Namespace is breaking migration

### ISSUE THREAD

**Issue by pseeger** [Sersid/yii2-config#1]
The namespace sersid\config\migrations prevents yii from loading the migration.

```
d:\Workspaces\Eclipse4CCWN\YiiGallery\Gallery>d:\xampp\php\php.exe yii migrate/up --migrationPath=@sersid/config/migrations
Yii Migration Tool (based on Yii v2.0.3)

Total 1 new migration to be applied:
        m141028_111823_config

Apply the above migration? (yes|no) [no]:yes
*** applying m141028_111823_config
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'm141028_111823_config' not found'

in D:\Workspaces\Eclipse4CCWN\YiiGallery\Gallery\vendor\yiisoft\yii2\console\controllers\MigrateController.php:113

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```

**Comment by Sersid** [comment]
Are you sure you migrationPath correct?
--migrationPath=@**vendor**/sersid/config/migrations

**Comment by pseeger** [comment]
@vendor/sersid/**config**/migrations won't work as the directory structure is /sersid/**yii2-config**/migrations. 
Possible --migrationPaths are:
@sersid/config/migrations
@vendor/sersid/yii2-config/migrations

**Comment by Sersid** [comment]
Fixed. Correct migrationPath is @vendor/sersid/yii2-config/migrations
Please update component using Composer
